# Generated by Django 4.2.20 on 2025-04-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_remove_order_items_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menu_items',
            new_name='items',
        ),
    ]
